# Название workflow
name: playwright

# Триггеры
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Джобы    
jobs:
  # Название джобы
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # Чекаут кода
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-java@v4.7.1
    - name: install npm
      run: npm ci
    - name: install Playwright Browsers
      run: npx playwright install --with-deps
    - name: test
      run: npm t

    # pw отчет
    - uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with: 
        name: allure-results
        path: allure-results
        retention-days: 2

    # Забираем результаты предыдущего запуска  
    - uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # Формируем из allure-results отчёт allure-report
    - uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    # Деплоим отчёт
    - name: deploy report
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        run: $ java "-DconfigFile=notifications/config.json" -jar notifications/allure-notifications-4.9.0.jar
    
     

